spring:
  jpa:
    show-sql: true
  datasource: #数据库配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lagou?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  mail: #邮件发送相关配置
    protocol: smtp
    host: smtp.163.com
    default-encoding: utf-8
    username: zhengjxnupt@163.com
    password: zjx111111